nhs-digital-gp-it-futures/MarketingPageAcceptanceTests

src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Actions/Pages/EditFeatures.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Actions/Pages/SolutionDescription.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Actions/Utils/PageAction.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Objects/Pages/EditFeatures.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Objects/Utils/RandomGenerator.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests/Tests/Steps/EditSolutionDescription.cs
- created util for generating randomness
- refactored existing logic for generating randomness to use beforementioned util
- changed character lengths for 'EditSolutionDescription' tests to represent currently set limits
=> Refactor random generation

src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Actions/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Objects/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests/Tests/Gherkin/PreviewMarketingPageSingleRole.txt, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests/Tests/Steps/PreviewMarketingPageSingleRole.cs
=> Completing AC 3 of 3005

src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Actions/Pages/SolutionDescription.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Actions/Utils/SqlHelper.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Objects/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Objects/Pages/SolutionDescription.cs
=> Updating to match latest dev work

src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Actions/Pages/Dashboard.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Actions/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Objects/Pages/Dashboard.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Objects/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTests/MarketingPageAcceptanceTests.Objects/Pages/SolutionDescription.cs
- commented some methods
- removed unused ones
- formatted code to be in line with the rest
- renamed one method to reflect better what it does
- left the 'GetMandatoryFieldNames' method from the other branch in as it can be useful
=> Code cleanup

src/MarketingPageAcceptanceTests.Actions/Collections/PageActionCollection.cs, src/MarketingPageAcceptanceTests.Actions/Pages/ContactDetails.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutOrganisation/ContactDetailsSection.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutOrganisation/ContactDetailsSection.feature.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/AboutOrganisation/ContactDetails.cs
Implement tests for scenarios
Currently failing  due to dev implementation pending
FYI @PhysicsJon
=> Display Marketing Page Form - Contact Details Section

src/MarketingPageAcceptanceTests.Actions/Pages/Common.cs, src/MarketingPageAcceptanceTests.Actions/Pages/ContactDetails.cs, src/MarketingPageAcceptanceTests.Actions/Pages/Dashboard.cs, src/MarketingPageAcceptanceTests.Objects/Pages/Dashboard.cs, src/MarketingPageAcceptanceTests.Objects/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutOrganisation/ContactDetailsSection.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutOrganisation/ContactDetailsSection.feature.cs
All tests now passing in both VS and CLI
=> Fixing broken methods and objects

src/MarketingPageAcceptanceTests.Actions/Pages/ContactDetails.cs, src/MarketingPageAcceptanceTests.TestData/Utils/Queries.cs, src/MarketingPageAcceptanceTests.TestData/Utils/SqlDataReaders/DataReaders.cs, src/MarketingPageAcceptanceTests.TestData/Utils/SqlHelper.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutOrganisation/EditContactDetails.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutOrganisation/EditContactDetails.feature.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutSolution/LastUpdatedDate.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutSolution/LastUpdatedDate.feature.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/AboutOrganisation/EditContactDetails.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/AboutSolution/LastUpdatedDate.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/ClientApplication/ConnectivityAndResolution/ConnectivityAndResolution.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/Features/EditFeatures.cs
implemented final lastUpdated scenario checking that saving contacts updates the column. Found a bug and created scenarios for it
=> 3520 part 2

src/MarketingPageAcceptanceTests.Actions/Pages/Common.cs, src/MarketingPageAcceptanceTests.Objects/Pages/BrowserBasedDashboard.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/BrowserBased/HardwareRequirementsAdditionalInformation.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/BrowserBased/HardwareRequirementsAdditionalInformation.feature.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/ClientApplication/HardwareRequirements/HardwareRequirements.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/ClientApplication/SharedClientApplicationTypesSteps.cs
=> Generalisation

src/MarketingPageAcceptanceTests.TestData/Solutions/ClientApplicationStrings.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/BrowserBased/DisplaySubDashboard.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeMobileOrTablet/SubDashboard.feature, src/MarketingPageAcceptanceTestsSpecflow/Steps/ClientApplication/BrowserBased/SubDashboard.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/ClientApplication/NativeMobileOrTablet/DisplayMarketingPageForm_NativeMobileOrTabletClientType.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/ClientApplication/SharedClientApplicationTypesSteps.cs
created scenarios for native mobile summing logic by reusing the scenarios for browser based
=> native mobile summing logic

src/MarketingPageAcceptanceTests.TestData/Solutions/ClientApplicationStringBuilder.cs, src/MarketingPageAcceptanceTests.TestData/Solutions/ClientApplicationStrings.cs, src/MarketingPageAcceptanceTests.TestData/Solutions/CreateSolutionDetails.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/ClientApplication/SharedClientApplicationTypesSteps.cs
Test Run Successful.
Total tests: 122
Passed: 121
Skipped: 1
Total time: 5.2752 Minutes
=> refactored ClientApplicationStrings to make it more maintainable

src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeDesktop/HardwareRequirementsAdditionalInformation.feature
Test Run Successful.
Total tests: 127
Passed: 126
Skipped: 1
Total time: 5.5798 Minutes
=> Added scenarios for hardware requirements

src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeDesktop/ConnectionDetails.feature
=> 3619 - Final test

src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeDesktop/HardwareRequirementsAdditionalInformation.feature
Test Run Successful.
Total tests: 155
Passed: 155
Total time: 6.9883 Minutes
=> enabled scenarios

src/MarketingPageAcceptanceTests.Actions/Collections/PageActionCollection.cs, src/MarketingPageAcceptanceTests.Actions/PageActions.cs, src/MarketingPageAcceptanceTests.Actions/Pages/NativeDesktopMemoryAndStorage.cs, src/MarketingPageAcceptanceTests.Objects/Collections/PageCollection.cs, src/MarketingPageAcceptanceTests.Objects/PageObjects.cs, src/MarketingPageAcceptanceTests.Objects/Pages/NativeDesktopMemoryStorage.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeDesktop/MemoryStorageProcessorResolution.feature, src/MarketingPageAcceptanceTestsSpecflow/Steps/ClientApplication/NativeDesktop/MemoryStorageProcessingAndResolution.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/ClientApplication/SharedBrowserBasedSteps.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/ClientApplication/SharedClientApplicationTypesSteps.cs, src/MarketingPageAcceptanceTestsSpecflow/Utils/EnvironmentVariables.cs, src/MarketingPageAcceptanceTestsSpecflow/Utils/UITest.cs
Tests all pass locally (156 pass, 0 fail, 0 skipped)
=> 3620 - Native desktop Memory, storage, processor and aspect ratio

src/MarketingPageAcceptanceTestsSpecflow/Features/Dashboard/DisplayOnDashboard.feature
Devs have enabled the public cloud page so the last test can be enabled
Local Test Run Successful.
Total tests: 169
Passed: 169
Total time: 8.3443 Minutes
=> enabled public cloud dashboard tests

src/MarketingPageAcceptanceTests.Actions/Collections/PageActionCollection.cs, src/MarketingPageAcceptanceTests.Actions/PageActions.cs, src/MarketingPageAcceptanceTests.Actions/Pages/PrivateCloud.cs, src/MarketingPageAcceptanceTests.Objects/Collections/PageCollection.cs, src/MarketingPageAcceptanceTests.Objects/PageObjects.cs, src/MarketingPageAcceptanceTests.Objects/Pages/PrivateCloud.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/HostingType/PrivateCloud.feature, src/MarketingPageAcceptanceTestsSpecflow/Steps/HostingType/SharedHostingTypeSteps.cs
Implemented private cloud scenarios
Test Run Successful.
Total tests: 182
Passed: 182
Total time: 10.0945 Minutes
=> 3641: ac tests

src/MarketingPageAcceptanceTests.Actions/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTests.Objects/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/Dashboard/DisplayOnDashboard.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ProductRoadmap/Roadmap.feature, src/MarketingPageAcceptanceTestsSpecflow/Steps/HostingType/SharedHostingTypeSteps.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/Roadmap/Roadmap.cs
Total tests: 200
Passing: 200
Failing: 0
=> Adding Edit Roadmap tests

src/MarketingPageAcceptanceTests.Actions/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTests.Objects/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTests.TestData/Solutions/Solution.cs, src/MarketingPageAcceptanceTests.TestData/Suppliers/CreateSupplier.cs, src/MarketingPageAcceptanceTests.TestData/Suppliers/Supplier.cs, src/MarketingPageAcceptanceTests.TestData/Utils/Queries.cs, src/MarketingPageAcceptanceTests.TestData/Utils/SqlDataReaders/DataReaders.cs, src/MarketingPageAcceptanceTests.TestData/Utils/SqlHelper.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutOrganisation/EditAboutSupplier.feature, src/MarketingPageAcceptanceTestsSpecflow/Steps/AboutOrganisation/EditAboutSupplier.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/HostingType/SharedHostingTypeSteps.cs
data model changes and test tweaks
=> 4228: Data model organisation updates

src/MarketingPageAcceptanceTestsSpecflow/Features/Dashboard/DisplayOnDashboard.feature
Added Supplier asserted integrations dashboard scenarios
=> 3666: Display Marketing Page Form - Supplier Asserted Integrations Section

src/MarketingPageAcceptanceTests.TestData/MarketingPageAcceptanceTests.TestData.csproj, src/MarketingPageAcceptanceTests.TestData/Solutions/CreateSolution.cs, src/MarketingPageAcceptanceTests.TestData/Utils/SqlReader.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/Dashboard/DisplayOnDashboard.feature, src/MarketingPageAcceptanceTestsSpecflow/Utils/EnvironmentVariables.cs, src/MarketingPageAcceptanceTestsSpecflow/Utils/tokens.json
Adding a retry policy to try and mitigate SQL deadlock issues
=> Retry policy

src/MarketingPageAcceptanceTests.TestData/Solutions/CreateSolutionDetails.cs, src/MarketingPageAcceptanceTests.TestData/Solutions/SolutionDetail.cs, src/MarketingPageAcceptanceTests.TestData/Utils/Queries.cs, src/MarketingPageAcceptanceTests.TestData/Utils/SqlHelper.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutOrganisation/EditContactDetails.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutSolution/EditIntegrations.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/EditClientApplicationTypes.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/Preview/AppearOnPreview.feature, src/MarketingPageAcceptanceTestsSpecflow/Steps/AboutOrganisation/EditContactDetails.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/AboutSolution/Suppliers_EditSupplierAssertedIntegrationsSection.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/ClientApplication/EditClientApplicationType.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/ClientApplication/HardwareRequirements/HardwareRequirements.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/CommonSteps.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/HostingType/SharedHostingTypeSteps.cs
added edit integrations scenarios, ignored as waiting for dev tasks
=> 3667: Suppliers - Edit Supplier Asserted Integrations Section

src/MarketingPageAcceptanceTestsSpecflow/Features/AboutSolution/EditIntegrations.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/Dashboard/DisplayOnDashboard.feature, src/MarketingPageAcceptanceTestsSpecflow/Steps/AboutSolution/Suppliers_EditSupplierAssertedIntegrationsSection.cs
=> 3667: Integrations

src/MarketingPageAcceptanceTestsSpecflow/Features/AboutOrganisation/EditAboutSupplier.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutSolution/LastUpdatedDate.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/BrowserBased/DisplaySubDashboard.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/BrowserBased/MobileFirst.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeDesktop/ConnectionDetails.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeDesktop/MemoryStorageProcessorResolution.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeDesktop/SubDashboard.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeDesktop/SupportedOperatingSystems.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeDesktop/ThirdPartyComponentsAndDeviceCapabilities.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeMobileOrTablet/ConnectionDetails.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeMobileOrTablet/MobileFirst.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeMobileOrTablet/OperatingSystemsSupported.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeMobileOrTablet/SubDashboard.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ClientApplication/NativeMobileOrTablet/ThirdPartyComponentsAndDeviceCapabilities.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/Dashboard/DisplayOnDashboard.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/Dashboard/SubmitForModeration.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/Preview/AppearOnPreview.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/ProductRoadmap/Roadmap.feature, src/MarketingPageAcceptanceTestsSpecflow/Steps/Hooks.cs, src/MarketingPageAcceptanceTestsSpecflow/Utils/EnvironmentVariables.cs, src/MarketingPageAcceptanceTestsSpecflow/Utils/UITest.cs
Created a before hook to determine whether to use authority or supplier in url based on feature name
=> 3678: prerequisite

src/MarketingPageAcceptanceTests.Actions/Pages/Common.cs, src/MarketingPageAcceptanceTests.Actions/Pages/Dashboard.cs, src/MarketingPageAcceptanceTests.TestData/Solutions/CreateSolutionDetails.cs, src/MarketingPageAcceptanceTests.TestData/Solutions/SolutionDetail.cs, src/MarketingPageAcceptanceTests.TestData/Utils/Queries.cs, src/MarketingPageAcceptanceTests.TestData/Utils/SqlHelper.cs, src/MarketingPageAcceptanceTestsSpecflow/Features/AboutSolution/EditImplementationTimescales.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/Dashboard/DisplayOnDashboard.feature, src/MarketingPageAcceptanceTestsSpecflow/Features/Preview/AppearOnPreview.feature, src/MarketingPageAcceptanceTestsSpecflow/Steps/AboutSolution/Suppliers_EditSupplierAssertedIntegrationsSection.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/CommonSteps.cs, src/MarketingPageAcceptanceTestsSpecflow/Steps/HostingType/SharedHostingTypeSteps.cs
Tests currently ignored, waiting for dev code
=> 3670: Suppliers - Edit Implementation Timescales

src/MarketingPageAcceptanceTests.AuthorityTests/Features/AuthorityDashboard/DisplayOnDashboard.feature, src/MarketingPageAcceptanceTests.AuthorityTests/MarketingPageAcceptanceTests.AuthorityTests.csproj
Will not pass on deployed dev currently as the deployed version of marketing-pages does not include the spelling correction
=> Updating test example to correct spelling

src/MarketingPageAcceptanceTests.Actions/Collections/PageActionCollection.cs, src/MarketingPageAcceptanceTests.Actions/PageActions.cs, src/MarketingPageAcceptanceTests.Actions/Pages/Capabilities.cs, src/MarketingPageAcceptanceTests.AuthorityTests/Features/AuthorityDashboard/DisplayOnDashboard.feature, src/MarketingPageAcceptanceTests.AuthorityTests/Features/Capabilities/DisplaySolutionsCapabilities.feature, src/MarketingPageAcceptanceTests.AuthorityTests/MarketingPageAcceptanceTests.AuthorityTests.csproj, src/MarketingPageAcceptanceTests.AuthorityTests/Utils/BeforeHook.cs, src/MarketingPageAcceptanceTests.Objects/Collections/PageCollection.cs, src/MarketingPageAcceptanceTests.Objects/PageObjects.cs, src/MarketingPageAcceptanceTests.Objects/Pages/Capabilities.cs, src/MarketingPageAcceptanceTests.Steps/Steps/Authority/Capabilities/DisplaySolutionsCapabilities.cs, src/MarketingPageAcceptanceTests.Steps/Utils/UITest.cs, src/MarketingPageAcceptanceTests.TestData/Capabilities/CapabilitiesGenerator.cs, src/MarketingPageAcceptanceTests.TestData/Capabilities/Capability.cs, src/MarketingPageAcceptanceTests.TestData/Capabilities/SolutionCapabilities.cs, src/MarketingPageAcceptanceTests.TestData/Utils/CsvConverter.cs, src/MarketingPageAcceptanceTests.TestData/Utils/Queries.cs
=> Adding authority capabilities screens tests (ignored for now)

src/MarketingPageAcceptanceTests.Actions/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTests.Objects/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTests.Steps/Steps/ClientApplication/BrowserSupported/BrowserSupported.cs, src/MarketingPageAcceptanceTests.Steps/Steps/CommonSteps.cs, src/MarketingPageAcceptanceTests.Steps/Steps/Hooks.cs, src/MarketingPageAcceptanceTests.Steps/Steps/Preview/AppearOnPreview.cs, src/MarketingPageAcceptanceTests.Steps/Utils/EnvironmentVariables.cs, src/MarketingPageAcceptanceTests.Steps/Utils/UITest.cs, src/MarketingPageAcceptanceTests.Steps/Utils/tokens.json, src/MarketingPageAcceptanceTests.SupplierTests/Features/ProductRoadmap/DownloadRoadmapAttachment.feature, src/MarketingPageAcceptanceTests.SupplierTests/Features/ProductRoadmap/Roadmap.feature, src/MarketingPageAcceptanceTests.TestData/Azure/AzureBlobStorage.cs, src/MarketingPageAcceptanceTests.TestData/MarketingPageAcceptanceTests.TestData.csproj, src/MarketingPageAcceptanceTests.TestData/Utils/AzureBlobStorage.cs
implemented negative scenarios, copied some azure blob code from DAPI to help when we're ready
=> 3657: Supplier Data - Download Roadmap Attachment

src/MarketingPageAcceptanceTests.Steps/Steps/Preview/AppearOnPreview.cs, src/MarketingPageAcceptanceTests.SupplierTests/Features/AboutSolution/DownloadIntegrationsAttachement.feature
implemented negative scenarios, positive scenario ignored as tech debt.
=> 3697: Supplier Data - Download NHS Assured Integrations Attachment

src/MarketingPageAcceptanceTests.Actions/Pages/Capabilities.cs, src/MarketingPageAcceptanceTests.AuthorityTests/Features/Capabilities/DispalySolutionsCapabilitysEpics.feature, src/MarketingPageAcceptanceTests.AuthorityTests/Features/Capabilities/DisplaySolutionsCapabilities.feature, src/MarketingPageAcceptanceTests.Objects/Pages/Capabilities.cs, src/MarketingPageAcceptanceTests.Objects/Pages/PreviewPage.cs, src/MarketingPageAcceptanceTests.Steps/Steps/Authority/Capabilities/DisplaySolutionsCapabilities.cs, src/MarketingPageAcceptanceTests.SupplierTests/Features/Preview/AppearOnPreview.feature, src/MarketingPageAcceptanceTests.TestData/Capabilities/CapabilitiesGenerator.cs, src/MarketingPageAcceptanceTests.TestData/Capabilities/Capability.cs, src/MarketingPageAcceptanceTests.TestData/Capabilities/SolutionCapabilities.cs, src/MarketingPageAcceptanceTests.TestData/Utils/CsvConverter.cs
=> Capability tests

src/MarketingPageAcceptanceTests.Steps/Utils/EnvironmentVariables.cs
changed local DB port to work with the local kube
=> local db port

src/MarketingPageAcceptanceTests.SupplierTests/Features/ClientApplication/BrowserBased/ConnectivityAndResolution.feature, src/MarketingPageAcceptanceTests.SupplierTests/Features/ClientApplication/BrowserBased/MobileFirst.feature, src/MarketingPageAcceptanceTests.SupplierTests/Features/ClientApplication/BrowserBased/PluginOrExtension.feature, src/MarketingPageAcceptanceTests.SupplierTests/Features/ClientApplication/NativeMobileOrTablet/MemoryAndStorageRequirements.feature, src/MarketingPageAcceptanceTests.SupplierTests/Features/ClientApplication/NativeMobileOrTablet/MobileFirst.feature
Still seeing 4 failing tests related to the submitForModeration URL error
Browser Supported - Validation on Submission
Submit for Moderation - Validation Error Message Anchors
Submit for Moderation - Mandatory Data Missing - Submit
Submit for Moderation - Mandatory Data Present - Submit
=> fixed failing tests which were expecting to be on dashboard

azure-pipelines.yml
changed replace tokens task name with guid
=> ambiguous task fix

src/MarketingPageAcceptanceTests.SupplierTests/Features/AboutSolution/DownloadIntegrationsAttachement.feature, src/MarketingPageAcceptanceTests.SupplierTests/Features/AuthorityProvidedDataDocument/DownloadAuthorityProvidedDataDocument.feature, src/MarketingPageAcceptanceTests.SupplierTests/Features/ClientApplication/BrowserBased/BrowserSupported.feature, src/MarketingPageAcceptanceTests.SupplierTests/Features/Dashboard/SubmitForModeration.feature, src/MarketingPageAcceptanceTests.SupplierTests/Features/ProductRoadmap/DownloadRoadmapAttachment.feature
also tagged out the document tests due to environmental changes
=> 5869: Disable the Submit for moderation button on MP

src/MarketingPageAcceptanceTests.Objects/Pages/HardwareRequirements.cs, src/MarketingPageAcceptanceTests.Objects/Pages/SupportedOperatingSystems.cs, src/MarketingPageAcceptanceTests.Steps/Steps/ClientApplication/SharedClientApplicationTypesSteps.cs, src/MarketingPageAcceptanceTests.Steps/Steps/CommonSteps.cs
updated locators for new text area
=> 6105: Dynamic TextArea Input

Dockerfile, entrypoint.sh, src/MarketingPageAcceptanceTests.Steps/appsettings.json
[AB#9371](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9371)
=> 9371: MPAC dockerisation

charts/mp-ac-tests/.helmignore, charts/mp-ac-tests/Chart.yaml, charts/mp-ac-tests/templates/NOTES.txt, charts/mp-ac-tests/templates/_helpers.tpl, charts/mp-ac-tests/templates/job.yaml, charts/mp-ac-tests/templates/serviceaccount.yaml, charts/mp-ac-tests/values.yaml
[AB#9372](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9372)
=> 9372: MP Helm Charts

README.md, charts/mp-ac-tests/templates/_helpers.tpl
Task [AB#9975](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9975)
Story [AB#9972](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9972)
=> Add revision to name of mp ac test
